ci:
  autoupdate_branch: "rewrite"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/winapps-org/pre-commit-rust
    rev: v1.1
    hooks:
      - id: fmt
      - id: clippy
      - id: cargo-check
