[package]
name = "winapps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
derive-new = "0.5.9"
home = "0.5.5"
lazy_static = "1.4.0"
serde = { version = "1.0.171", features = ["derive"] }
thiserror = "1.0.49"
toml = "0.8.2"
tracing = "0.1.37"
