name: Rust Fmt

on:
  push:
    branches: [ "rewrite" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Formatting Code
        run: cargo fmt --all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Fix Formatt
          title: Formatt Code
          body: Running cargo fmt --all results
          branch: rewrite
