name: Rust Fmt

on:
  push:
    branches: [ "rewrite" ]

permissions:
  pull-requests: write
    
env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Formatting Code
        run: cargo fmt --all --verbose
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "rewrite"
          source_branch: rewrite
