name: Rust Fmt

on:
  push:
    branches: [ "rewrite" ]

permissions:
  pull-requests: write
    
env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Formatting Code
        run: cargo fmt --all --verbose
      - name: Create Pull Request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "Bot Fix: Formatting" --body "Fix formatting with cargo fmt"
